export enum AuthStages {
    CHECKING_AUTH = 'CHECKING_AUTH',
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
    AUTHENTICATING = 'AUTHENTICATING',
}

export enum AuthTransitionTypes {
    // Inner
    CHECKING_AUTH__NOT_AUTHENTICATED = 'CHECKING_AUTH__NOT_AUTHENTICATED',
    NOT_AUTHENTICATED__AUTHENTICATING = 'NOT_AUTHENTICATED__AUTHENTICATING',
    AUTHENTICATING__NOT_AUTHENTICATED = 'AUTHENTICATING__NOT_AUTHENTICATED',
    // To product list
    CHECKING_AUTH__LOADING_PRODUCTS = 'CHECKING_AUTH__LOADING_PRODUCTS',
    AUTHENTICATING__LOADING_PRODUCTS = 'AUTHENTICATING__LOADING_PRODUCTS',
}
